// src/App.jsx — Generated by VIA for: Create a simple full stack web application with user login, dashboard, backend API, database connection, and responsive frontend UI.
import { useState, useEffect } from "react";
import { toast, ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const COLS = ["To Do", "In Progress", "Review", "Done"];
const COL_COLORS = {
  "To Do":       "border-gray-300 bg-gray-50",
  "In Progress": "border-blue-300 bg-blue-50",
  "Review":      "border-amber-300 bg-amber-50",
  "Done":        "border-green-300 bg-green-50",
};
const PRIORITY = { High:"bg-red-100 text-red-700", Medium:"bg-amber-100 text-amber-700", Low:"bg-gray-100 text-gray-600" };

const SEED = [
  { id:1, title:"Design system setup", col:"Done",        priority:"High",   assignee:"Alice" },
  { id:2, title:"API integration",     col:"In Progress", priority:"High",   assignee:"Bob"   },
  { id:3, title:"Write unit tests",    col:"To Do",       priority:"Medium", assignee:"Carol" },
  { id:4, title:"UI review",           col:"Review",      priority:"Low",    assignee:"Dave"  },
];

export default function App() {
  const [cards, setCards] = useState(SEED);
  const [dragging, setDragging] = useState(null);
  const [over, setOver] = useState(null);
  const [showForm, setShowForm] = useState(false);
  const [form, setForm] = useState({ title:"", priority:"Medium", assignee:"" });

  const addCard = (e) => {
    e.preventDefault();
    if (!form.title.trim()) { toast.error("Title required"); return; }
    setCards(c => [...c, { id: Date.now(), col:"To Do", ...form }]);
    setForm({ title:"", priority:"Medium", assignee:"" }); setShowForm(false);
    toast.success("Card added!");
  };
  const deleteCard = (id) => setCards(c => c.filter(x => x.id !== id));
  const moveCard = (col) => {
    if (dragging === null) return;
    setCards(c => c.map(x => x.id === dragging ? {...x, col} : x));
    setDragging(null); setOver(null);
  };

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#f0fdf4" }}>
      <ToastContainer position="top-right" autoClose={3000} />
      <nav className="bg-white border-b border-gray-100 shadow-sm sticky top-0 z-50">
        <div className="max-w-full px-6 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3"><span className="text-2xl">📊</span><span className="font-bold text-gray-900">Create A Simple Full Stack Web Application With</span></div>
          <button onClick={() => setShowForm(true)} className="btn-primary">+ Add Card</button>
        </div>
      </nav>
      <main className="px-6 py-8 overflow-x-auto">
        <div className="flex gap-5 min-w-max">
          {COLS.map(col => (
            <div key={col}
              onDragOver={e => { e.preventDefault(); setOver(col); }}
              onDrop={() => moveCard(col)}
              className={`w-72 rounded-2xl border-2 ${COL_COLORS[col] || "border-gray-200 bg-gray-50"} p-4 space-y-3 transition-all ${over === col ? "ring-2 ring-offset-1" : ""}`}
              style={{ ringColor: over === col ? "#10b981" : undefined }}>
              <div className="flex items-center justify-between">
                <h2 className="font-semibold text-gray-800">{col}</h2>
                <span className="text-xs bg-white border border-gray-200 text-gray-500 px-2 py-0.5 rounded-full">
                  {cards.filter(c => c.col === col).length}
                </span>
              </div>
              {cards.filter(c => c.col === col).map(card => (
                <div key={card.id} draggable
                  onDragStart={() => setDragging(card.id)}
                  className="bg-white rounded-xl border border-gray-100 shadow-sm p-3 space-y-2 cursor-grab active:cursor-grabbing hover:shadow-md transition-all">
                  <div className="flex justify-between items-start gap-2">
                    <p className="font-medium text-gray-900 text-sm leading-snug">{card.title}</p>
                    <button onClick={() => deleteCard(card.id)} className="text-gray-300 hover:text-red-400 text-xs shrink-0">✕</button>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${PRIORITY[card.priority] || PRIORITY.Medium}`}>{card.priority}</span>
                    {card.assignee && <span className="text-xs text-gray-400">👤 {card.assignee}</span>}
                  </div>
                </div>
              ))}
              <button onClick={() => { setForm(f => ({...f, _col: col})); setShowForm(true); }}
                className="w-full text-sm text-gray-400 hover:text-gray-700 py-2 border-2 border-dashed border-gray-200 rounded-xl hover:border-gray-300 transition-all">
                + Add card
              </button>
            </div>
          ))}
        </div>
      </main>
      {showForm && (
        <div className="fixed inset-0 bg-black/40 z-50 flex items-center justify-center p-4">
          <div className="bg-white rounded-2xl shadow-2xl w-full max-w-sm p-6 space-y-4">
            <div className="flex justify-between items-center"><h2 className="text-xl font-bold">New Card</h2><button onClick={() => setShowForm(false)} className="text-gray-400 text-xl">✕</button></div>
            <form onSubmit={addCard} className="space-y-3">
              <input className="input" placeholder="Card title *" value={form.title} onChange={e => setForm({...form, title:e.target.value})} required />
              <select className="input" value={form.priority} onChange={e => setForm({...form, priority:e.target.value})}>
                <option>High</option><option>Medium</option><option>Low</option>
              </select>
              <input className="input" placeholder="Assignee" value={form.assignee} onChange={e => setForm({...form, assignee:e.target.value})} />
              <div className="flex gap-3"><button type="submit" className="btn-primary">Add</button><button type="button" onClick={() => setShowForm(false)} className="btn-secondary">Cancel</button></div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
}
